#!/bin/bash

echo -n "Branch?: "
read branch

cp -r ~/.config/hypr ~/Github/HyprArch/$branch/.config

cp -r ~/.config/{hypr,kitty,starship.toml,waybar,lvim,grub_themes,sddm_themes,wofi,rofi,swaylock,fish,dunst} ~/Github/HyprArch/$branch/config
cp ~/.bashrc ~/.bash_aliases ~/.bash_vars ~/Github/HyprArch/$branch/home/
cp ~/Scripts/* ~/Github/HyprArch/$branch/scripts
sleep 0.2

echo "[+] Files copied succesfully"
sleep 0.2
ps aux | pgrep github-desktop &> /dev/null
if ! [ $? -eq 0 ]; then
    echo "[+] Openning github-desktop"
    exec github-desktop &> /dev/null & disown
    sleep 1.75
fi
echo "[+] Program terminated!"
